//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_tutorial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_users
    {
        public int id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
        public Nullable<bool> isExists { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<bool> role { get; set; }
    }
}
